function TEM_SWAP(prn)

clc
close all
clearvars

prn = 1;
% LCpower(prn)
% se prn=1 salva le figure power.eps
%% Local Variables
% Impostazione Figura

%%
lincol5=[0 0 0];            % black
lincol7=0.35*[1 1 1];       % gray
lincol3=0.70*[1 1 1];        % gray
lincol8=0.25*[1 1 1];
linwid1=0.5;              % spessore 1
linwid2=1.5;              % spessore 2

nx = 2;			% Numero di figure in orizzontale
ny = 7;			% Numero di figure in verticale
bx = 0.3;	    % Margini sinistro  e destro    [cm]
by = 0.35;		% Margini superiore e inferiore [cm]
fx = [3.7 3.2];		% Larghezza primo riquadro interno [cm]
fy = 1.7;	        % Altezza riquadri interni   [cm]
dx = 0.6;		% Distanza orizzontale tra i riquadri [cm]
dy = 0.4;       % Distanza verticale tra i riquadri   [cm]
ox = 0.4;		% Offset orizzontale [cm]
oy = 0.03;		% Offset verticale   [cm]
ospl = 0.0;
fnt  = 8;		% Dimensione dei font per gli assi
fnl  = 8;		% Dimensione dei font per le labels
fnl2 = 7;		% Dimensione dei font per le labels

fwidth  = sum(fx)+(nx-1)*dx+2*bx+ox
fheigth = ny*fy+(ny-1)*dy+2*by+ospl;

if fwidth > 8.5
    disp('Error. Plot wider than single column')
    return
end

% Color1 = lincol5;
% Color2 = lincol7;
% Color3 = lincol3;

blue = [57 106 177]./255;
red = [204 37 41]./255;
black = [83 83 83]./255;
green = [62 150 81]./255;
brown = [146 36 40]./255;
purple = [107 76 154]./255;


%% Creazione Figura
figure('Renderer', 'Painters',...
    'units','centimeters',...
    'position',[bx, by, fwidth, fheigth], ...
    'PaperUnits','centimeters', ...
    'PaperOrientation','portrait', ...
    'PaperPosition',[bx, by, fwidth, fheigth], ...
    'PaperType','A4', ...
    'Color','white' ...
    );
%%
% Creazione Riquadri e Grafici
% #format table ## [WaveView Analyzer] saved 16:33:34 Sun Mar 17 2019
% XVAL Ir Irdw Irup Is Isdw Isup It Itdw Itup Mcbn.Iarc Vr Vrdw Vrup Vs Vsdw Vsup Vt Vtdw Vtup neu Vndw Vnup

load('TEM_SWAP_TRAN_SHOOTING_1.mat');
load('TEM_SWAP_TRAN_SHOOTING_2.mat');                                      % da usare solo per gli inset a fine periodo.
load('TEM_SWAP_TRAN_STARTUP.mat');

F0              = 50;
tA              = 150e-3;
tB              = tA + 10/F0;
tC              = tA + 1000/F0;
DEC             = 5;

for hor=1:nx
    for ver=1:ny
        h(ver,hor)=axes(...
            'units','centimeters',...
            'position',[bx+(hor-1)*(fx(max(hor-1,1))+dx)+ox, by+(ny-ver)*(fy+dy)+oy, fx(hor) fy],...
            'fontsize',fnt,...
            'fontname','helvetica',...
            'fontangle','normal',...
            'visible','on', ...
            'Color','none', ...
            'box','on', ...
            'XTickLabel', [], ...
            'YTickLabel', [], ...
            'XTick', [], ...
            'Ytick', []);

        if ver == 1
            line(TEM_SWAP_TRAN_STARTUP.time(1:DEC:end),TEM_SWAP_TRAN_STARTUP.slk_ia(1:DEC:end),'Color', black, ...
                'LineWidth', linwid1, 'Linestyle','-');

            hold on

            if hor == 2
                line(TEM_SWAP_TRAN_SHOOTING_1.time(1:DEC:end),TEM_SWAP_TRAN_SHOOTING_1.slk_ia(1:DEC:end),'Color', red, ...
                    'LineWidth', linwid1, 'Linestyle','-.');
            end
            grid on

        elseif ver == 2

            line(TEM_SWAP_TRAN_STARTUP.time(1:DEC:end),TEM_SWAP_TRAN_STARTUP.BmC1_pos(1:DEC:end)*2,'Color', black, ...
                'LineWidth', linwid1, 'Linestyle','-');

            hold on

            if hor == 2
                line(TEM_SWAP_TRAN_SHOOTING_1.time(1:DEC:end),TEM_SWAP_TRAN_SHOOTING_1.BmC1_pos(1:DEC:end)*2,'Color', red, ...
                    'LineWidth', linwid1, 'Linestyle','-.');
            end
            grid on

            ylim([398 432]*1e3)

        elseif ver == 3

            line(TEM_SWAP_TRAN_STARTUP.time(1:DEC:end),TEM_SWAP_TRAN_STARTUP.CmA1_pow(1:DEC:end),'Color', black, ...
                'LineWidth', linwid1, 'Linestyle','-');

            hold on

            if hor == 2
                line(TEM_SWAP_TRAN_SHOOTING_1.time(1:DEC:end),TEM_SWAP_TRAN_SHOOTING_1.CmA1_pow(1:DEC:end),'Color', red, ...
                    'LineWidth', linwid1, 'Linestyle','-.');
            end
            grid on

        elseif ver == 4

            line(TEM_SWAP_TRAN_STARTUP.time(1:DEC:end),TEM_SWAP_TRAN_STARTUP.CmA1_i_up_a(1:DEC:end),'Color', black, ...
                'LineWidth', linwid1, 'Linestyle','-');

            hold on

            if hor == 2
                line(TEM_SWAP_TRAN_SHOOTING_1.time(1:DEC:end),TEM_SWAP_TRAN_SHOOTING_1.CmA1_i_up_a(1:DEC:end),'Color', red, ...
                    'LineWidth', linwid1, 'Linestyle','-.');
            end
            grid on

        elseif ver == 5

            line(TEM_SWAP_TRAN_STARTUP.time(1:DEC:end),TEM_SWAP_TRAN_STARTUP.CmC1_drv_up_a(1:DEC:end),'Color', black, ...
                'LineWidth', linwid1, 'Linestyle','-');

            hold on

            if hor == 2
                line(TEM_SWAP_TRAN_SHOOTING_1.time(1:DEC:end),TEM_SWAP_TRAN_SHOOTING_1.CmC1_drv_up_a(1:DEC:end),'Color', red, ...
                    'LineWidth', linwid1, 'Linestyle','-.');
            end
            grid on


        elseif ver == 6

            line(TEM_SWAP_TRAN_STARTUP.time(1:DEC:end),TEM_SWAP_TRAN_STARTUP.CmC1_Arm_up_a_vcap1(1:DEC:end),'Color', black, ...
                'LineWidth', linwid1, 'Linestyle','-');

            hold on

            if hor == 2
                line(TEM_SWAP_TRAN_SHOOTING_1.time(1:DEC:end),TEM_SWAP_TRAN_SHOOTING_1.CmC1_Arm_up_a_vcap1(1:DEC:end),'Color', red, ...
                    'LineWidth', linwid1, 'Linestyle','-.');
            end
            grid on

        elseif ver == 7

            line(TEM_SWAP_TRAN_STARTUP.time(1:DEC:end),TEM_SWAP_TRAN_STARTUP.omega9(1:DEC:end),'Color', black, ...
                'LineWidth', linwid1, 'Linestyle','-');

            hold on

            if hor == 2
                line(TEM_SWAP_TRAN_SHOOTING_1.time(1:DEC:end),TEM_SWAP_TRAN_SHOOTING_1.omega9(1:DEC:end),'Color', red, ...
                    'LineWidth', linwid1, 'Linestyle','-.');
            end
            grid on
        end



        if hor == 1 && ver ~= 7
            xlim([0 1])
        end

        if hor == 2
            if ver ~= 7
                xlim([tA tB])
            else
                xlim([tA tC])
            end
        end


        if ver == 1 && hor == 1
            format_ticks(h(ver,hor),{'$ $','$ $','$ $','$ $','$ $','$ $'},...
                {'$-2.5$','$ $','$0$','$ $','$2.5$'},...
                (linspace(0,1,6)), (linspace(-2.5e3,2.5e3,5)),...
                [],[],[0.020 0.020]);

            %             axlbl={'$$ $$','$$ \imath_{\mathrm{ac}} \, (\mathrm{{MMC}_R}) \, [\mathrm{kA}] $$'};
            axlbl={'$$ $$','$$ \imath_{a} \, [\mathrm{kA}] $$'};
            text(0.015,0.74,axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );

        elseif ver == 2 && hor == 1
            format_ticks(h(ver,hor),{'$ $','$ $','$ $','$ $','$ $','$ $'},...
                {'$400$','$ $','$416$','$ $','$432$'},...
                (linspace(0,1,6)), (linspace(200,216,5)*2e3),...
                [],[],[0.020 0.020]);

            %             axlbl={'$$ $$','$$ v_{\mathrm{dc}} \, (\mathrm{{MMC}_S}) \, [\mathrm{kV}] $$'};
            axlbl={'$$ $$','$$ v_{\mathrm{dc}} \, [\mathrm{kV}] $$'};
            text(0.015,0.74,axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );


        elseif ver == 3 && hor == 1
            format_ticks(h(ver,hor),{'$ $','$ $','$ $','$ $','$ $','$ $'},...
                {'$-30$','$ $','$270$','$ $','$570$'},...
                (linspace(0,1,6)), (linspace(-30,570,5)*1e6),...
                [],[],[0.020 0.020]);

            %              axlbl={'$$ $$','$$ P \, (\mathrm{{MMC}_S}) \, [\mathrm{MW}] $$'};
            axlbl={'$$ $$','$$ P \, [\mathrm{MW}] $$'};
            text(0.014,0.74,axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );


        elseif ver == 4 && hor == 1
            format_ticks(h(ver,hor),{'$ $','$ $','$ $','$ $','$ $','$ $'},...
                {'$-0.5$','$ $','$0.6$','$ $','$1.7$'},...
                (linspace(0,1,6)), (linspace(-500,1.7e3,5)),...
                [],[],[0.020 0.020]);

            %             axlbl={'$$ $$','$$ i_{\mathrm{up}_a} \, (\mathrm{{MMC}_R}) \, [\mathrm{kA}] $$'};
            axlbl={'$$ $$','$$ \imath_{u_a} \, [\mathrm{kA}] $$'};
            text(0.014,0.74,axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );

        elseif ver == 5 && hor == 1
            format_ticks(h(ver,hor),{'$0$','$0.2$','$0.4$','$0.6$','$0.8$','$1$'},...
                {'$0$','$ $','$0.6$','$ $','$0.9$'},...
                (linspace(0,1,6)), (linspace(0,1.2,5)),...
                [],[],[0.040 0.020]);

            axlbl={'$$t [\mathrm{s}] $$','$$ m_{u_a} \, [\mathrm{kV}] $$'};
            text(0.014,0.74,axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );


        elseif ver == 6 && hor == 1
            format_ticks(h(ver,hor),{'$0$','$0.2$','$0.4$','$0.6$','$0.8$','$1$'},...
                {'$2.95$','$ $','$3.30$','$ $','$3.65$'},...
                (linspace(0,1,6)), (linspace(2.95,3.65,5)*1e3),...
                [],[],[0.040 0.020]);

          axlbl={'$$t [\mathrm{s}] $$','$$ v_{u_a}^{\mathrm{cap1}} \, [\mathrm{kV}] $$'};
            text(0.014,0.74,axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );


        elseif ver == 7 && hor == 1
            format_ticks(h(ver,hor),{'$0$','$20$','$40$','$60$','$80$','$100$'},...
                {'$-15$','$ $','$0$','$ $','$15$'},...
                (linspace(0,100,6)), (linspace(0.985,1.015,5)),...
                [],[],[0.040 0.020]);

            axlbl={'$$t [\mathrm{s}]$$','$$ \Delta\omega_{\mathrm{G_9}} [10^{-3} \, \mathrm{p.u.}] $$'};
            text(0.017,0.74,axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );

            text(0.90,0.01,axlbl{1}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );


            % HOR == 2
        elseif ver == 1 && hor == 2
            format_ticks(h(ver,hor),{'$ $','$ $','$ $','$ $','$ $'},...
                {'$ $','$ $','$ $','$ $','$ $'},...
                (linspace(tA,tB,5)), (linspace(-2.5e3,2.5e3,5)),...
                [],[],[0.020 0.020]);

        elseif ver == 2 && hor == 2
            format_ticks(h(ver,hor),{'$ $','$ $','$ $','$ $','$ $'},...
                {'$ $','$ $','$ $','$ $','$ $'},...
                (linspace(tA,tB,5)), (linspace(200,216,5)*2e3),...
                [],[],[0.020 0.020]);

        elseif ver == 3 && hor == 2
            format_ticks(h(ver,hor),{'$ $','$ $','$ $','$ $','$ $'},...
                {'$ $','$ $','$ $','$ $','$ $'},...
                (linspace(tA,tB,5)), (linspace(-30,570,5)*1e6),...
                [],[],[0.020 0.020]);

        elseif ver == 4 && hor == 2
            format_ticks(h(ver,hor),{'$ $','$ $','$ $','$ $','$ $'},...
                {'$ $','$ $','$ $','$ $','$ $'},...
                (linspace(tA,tB,5)), (linspace(-500,1.7e3,5)),...
                [],[],[0.020 0.020]);

        elseif ver == 5 && hor == 2
            format_ticks(h(ver,hor),{'$ $','$ $','$ $','$ $','$ $'},...
                {'$ $','$ $','$ $','$ $','$ $'},....
                (linspace(tA,tB,5)), (linspace(0,1.2,5)),...
                [],[],[0.020 0.020]);

        elseif ver == 6 && hor == 2
            format_ticks(h(ver,hor),{'$0.15$','$ $','$0.25$','$ $','$0.35$'},...
                {'$ $','$ $','$ $','$ $','$ $'},....
                (linspace(tA,tB,5)), (linspace(2.95,3.65,5)*1e3),...
                [],[],[0.020 0.020]);

        elseif ver == 7 && hor == 2
            format_ticks(h(ver,hor),{'$0.15$','$ $','$10.15$','$ $','$20.15$'},...
                {'$ $','$ $','$ $','$ $','$ $'},...
                (linspace(tA,tC,5)), (linspace(0.985,1.015,5)),...
                [],[],[0.040 0.020]);

            axlbl={'$$t [\mathrm{s}]$$','$$ \Delta\omega_{\mathrm{G_9}} [\mathrm{p.u.}] $$'};
            text(0.88,0.01,axlbl{1}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );
        end

    end
end


%% LEFT SIDE INSETS
% INSET 1
inset1 = axes(...
    'units','normalized',...
    'position',[0.30 0.775, 0.18 0.05],...
    'fontsize',fnt,...
    'fontname','helvetica',...
    'fontangle','normal',...
    'visible','on', ...
    'Color','none', ...
    'box','on', ...
    'XTickLabel', [], ...
    'YTickLabel', [], ...
    'XTick', [], ...
    'Ytick', [], ...
    'XLim', [100-1/F0 100], ...
    'YLim', [400e3 408e3]);


line(TEM_SWAP_TRAN_STARTUP.time(1:DEC:end),TEM_SWAP_TRAN_STARTUP.BmC1_pos(1:DEC:end)*2,'Color', black, ...
    'LineWidth', linwid1, 'Linestyle','-');

hold on

line(TEM_SWAP_TRAN_SHOOTING_2.time(1:DEC:end),TEM_SWAP_TRAN_SHOOTING_2.BmC1_pos(1:DEC:end)*2,'Color', red, ...
    'LineWidth', linwid1, 'Linestyle','-');
grid on

set(inset1, 'Xgrid', 'on', 'Ygrid', 'on');

format_ticks(inset1,{'$99.98$','$ $','$99.99$','$ $','$100$'},...
    {'$400$','$ $','$404$','$ $', '$408$'},...
    linspace(100-1/F0,100,5),  linspace(400e3,408e3,5),[],[],[0.080 0.010]);
axlbl={'$$ $$','$$ $$'};

% INSET 2
inset2 = axes(...
    'units','normalized',...
    'position',[0.30 0.61, 0.18 0.04],...
    'fontsize',fnt,...
    'fontname','helvetica',...
    'fontangle','normal',...
    'visible','on', ...
    'Color','none', ...
    'box','on', ...
    'XTickLabel', [], ...
    'YTickLabel', [], ...
    'XTick', [], ...
    'Ytick', [], ...
    'XLim', [100-1/F0 100], ...
    'YLim', [370e6 400e6]);


line(TEM_SWAP_TRAN_STARTUP.time(1:DEC:end),TEM_SWAP_TRAN_STARTUP.CmA1_pow(1:DEC:end),'Color', black, ...
    'LineWidth', linwid1, 'Linestyle','-');

hold on

line(TEM_SWAP_TRAN_SHOOTING_2.time(1:DEC:end),TEM_SWAP_TRAN_SHOOTING_2.CmA1_pow(1:DEC:end),'Color', red, ...
    'LineWidth', linwid1, 'Linestyle','-');
grid on

grid on

set(inset2, 'Xgrid', 'on', 'Ygrid', 'on');

format_ticks(inset2,{'$99.98$','$ $','$99.99$','$ $','$100$'},...
    {'$370$','$ $','$385$','$ $', '$400$'},...
    linspace(100-1/F0,100,5),  linspace(370e6,400e6,5),[],[],[0.080 0.010]);
axlbl={'$$ $$','$$ $$'};


%% RIGHT-SIDE INSETS


% INSET 3
inset3 = axes(...
    'units','normalized',...
    'position',[0.85 0.78, 0.083 0.045],...
    'fontsize',fnt,...
    'fontname','helvetica',...
    'fontangle','normal',...
    'visible','on', ...
    'Color','none', ...
    'box','on', ...
    'XTickLabel', [], ...
    'YTickLabel', [], ...
    'XTick', [], ...
    'Ytick', [], ...
    'XLim', [0.15 0.15+2/F0], ...
    'YLim', [400e3 408e3]);


line(TEM_SWAP_TRAN_STARTUP.time(1:DEC:end),TEM_SWAP_TRAN_STARTUP.BmC1_pos(1:DEC:end)*2,'Color', black, ...
    'LineWidth', linwid1, 'Linestyle','-');

hold on

line(TEM_SWAP_TRAN_SHOOTING_1.time(1:DEC:end),TEM_SWAP_TRAN_SHOOTING_1.BmC1_pos(1:DEC:end)*2,'Color', red, ...
    'LineWidth', linwid1, 'Linestyle','-');
grid on

set(inset3, 'Xgrid', 'on', 'Ygrid', 'on');

format_ticks(inset3,{'$0.15$','$ $','$0.19$'},...
    {'$403.8$','$ $','$404.3$','$ $', '$404.8$'},...
    linspace(0.15,0.15+2/F0,3),  linspace(400e3,408e3,5),[],[],[0.080 0.010]);
axlbl={'$$ $$','$$ $$'};

% INSET 4
inset4 = axes(...
    'units','normalized',...
    'position',[0.76 0.61, 0.17 0.04],...
    'fontsize',fnt,...
    'fontname','helvetica',...
    'fontangle','normal',...
    'visible','on', ...
    'Color','none', ...
    'box','on', ...
    'XTickLabel', [], ...
    'YTickLabel', [], ...
    'XTick', [], ...
    'Ytick', [], ...
    'XLim', [0.15 0.15+3/F0], ...
    'YLim', [370e6 392e6]);


line(TEM_SWAP_TRAN_STARTUP.time(1:DEC:end),TEM_SWAP_TRAN_STARTUP.CmA1_pow(1:DEC:end),'Color', black, ...
    'LineWidth', linwid1, 'Linestyle','-');

hold on

line(TEM_SWAP_TRAN_SHOOTING_1.time(1:DEC:end),TEM_SWAP_TRAN_SHOOTING_1.CmA1_pow(1:DEC:end),'Color', red, ...
    'LineWidth', linwid1, 'Linestyle','-');
grid on

grid on

set(inset4, 'Xgrid', 'on', 'Ygrid', 'on');

format_ticks(inset4,{'$0.15$','$ $','$ $','$ $','$0.21$'},...
    {'$370$','$ $','$381$','$ $', '$392$'},...
    linspace(0.15,0.15+3/F0,5),  linspace(370e6,392e6,5),[],[],[0.080 0.010]);
axlbl={'$$ $$','$$ $$'};


if(prn)
    print -loose -painters -depsc2 ..\Figures\TEM_SWAP.eps
end